const http = require('http');


const server = http.createServer( (req, res) => {
    console.log("Log generated by INdex file from node app ");
    res.write("Welcome to Node app");
    res.end();


});

server.listen(3000); /* We were hard coding the port number each time */

/*

OS (Linux)
NodeJS (Software / CLI)
Port (3000)

*/
